services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://birds-postgresdb:5432/BIRDdb
      SPRING_DATASOURCE_USERNAME: BIRD
      SPRING_DATASOURCE_PASSWORD: BIRD_PWD
    depends_on:
      - birds-postgresdb

  birds-postgresdb:
    container_name: birds-postgresdb
    image: postgres:latest
    volumes:
      - local-deployment_birds-postgres-data:/var/lib/docker/volumes/local-deployment_bird-postgres-data/_data
    ports:
        - 5433:5432
    environment:
      POSTGRES_PASSWORD: BIRD_PWD
      POSTGRES_DB: BIRDdb
      POSTGRES_USER: BIRD

volumes:
  local-deployment_birds-postgres-data: