server:
  port: 8080
  servlet:
    context-path: /birds/api/v1
spring:
  datasource:
    url: jdbc:h2:mem:birds
    username: rd
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true