server:
  port: 8080
  servlet:
    context-path: /birds/api/v1
spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/BIRDdb
    driver.class-name: org.postgresql.Driver
    username: BIRD
    password: BIRD_PWD
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect