server:
  port: 8080
  servlet:
    context-path: /birds/api/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BIRD
    driver.class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect